main:
  - name: Sobre
    url: /
    weight: 10

  - name: Publicações
    url: /publications/
    weight: 11

  # - name: Talks
  #   url: /#talks
  #   weight: 12

  # - name: News
  #   url: /#news
  #   weight: 13

  - name: Experiência
    url: experience/
    weight: 20

  #- name: Projetos
  #  url: projects/
  #  weight: 30

  # - name: Courses
  #   url: courses/
  #   weight: 40